// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241114062250_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Domains.Languages.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Culture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRtl")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shortcut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Languages", (string)null);
                });

            modelBuilder.Entity("Core.Domains.Languages.StringResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupKey")
                        .HasColumnType("int");

                    b.Property<string>("GroupKeyString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("StringResources");
                });

            modelBuilder.Entity("Core.HomePage.HomePage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChooseUsId")
                        .HasColumnType("int");

                    b.Property<int?>("ClientSaysId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HomePageInfoId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("OurCompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("OurEmployeesId")
                        .HasColumnType("int");

                    b.Property<int?>("RegularBlogsId")
                        .HasColumnType("int");

                    b.Property<int?>("ServicesId")
                        .HasColumnType("int");

                    b.Property<int?>("SliderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WhoWeAreId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkShowCaseId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkingProcessId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChooseUsId");

                    b.HasIndex("ClientSaysId");

                    b.HasIndex("HomePageInfoId");

                    b.HasIndex("OurCompanyId");

                    b.HasIndex("OurEmployeesId");

                    b.HasIndex("RegularBlogsId");

                    b.HasIndex("ServicesId");

                    b.HasIndex("SliderId");

                    b.HasIndex("WhoWeAreId");

                    b.HasIndex("WorkShowCaseId");

                    b.HasIndex("WorkingProcessId");

                    b.ToTable("HomePages", (string)null);
                });

            modelBuilder.Entity("Core.HomePage.HomePageInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MetaAuthor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaKeywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaPublisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HomePageInfos");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.ChooseUs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ChooseUs");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.ClientSays", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ClientSays");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.ClientSaysItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Branch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientSaysId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientSaysId");

                    b.ToTable("ClientSaysItems");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.Footer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Footers");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.FooterService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FooterId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FooterId");

                    b.ToTable("FooterServices");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ServiceItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceItemId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.NavBarItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasSubItem")
                        .HasColumnType("bit");

                    b.Property<int?>("HomePageId")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HomePageId");

                    b.ToTable("NavBarItems", (string)null);
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.NavBarItemSubItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NavBarItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NavBarItemId");

                    b.ToTable("NavBarItemSubItems", (string)null);
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.OurCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OurCompanys");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.OurEmployees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OurEmployees");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.OurEmployeesItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Branch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OurEmployeesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OurEmployeesId");

                    b.ToTable("OurEmployeesItems");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChooseUsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChooseUsId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.QuickLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FooterId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FooterId");

                    b.ToTable("QuickLinks");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.RegularBlogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RegularBlogs");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.RegularBlogsItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RegularBlogsId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RegularBlogsId");

                    b.ToTable("RegularBlogsItems");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.ServiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("ServicesId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceItems");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sliders");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.SocialLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HomePageInfoId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HomePageInfoId");

                    b.ToTable("SocialLink");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.WhoWeAre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("WhoWeAres");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.WhoWeAreItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WhoWeAreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WhoWeAreId");

                    b.ToTable("WhoWeAreItems");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.WorkShowCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("WorkShowCases");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.WorkShowCaseNavBar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasSubItem")
                        .HasColumnType("bit");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkShowCaseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkShowCaseId")
                        .IsUnique();

                    b.ToTable("WorkShowCaseNavBars");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.WorkShowCaseNavBarItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkShowCaseNavBarId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkShowCaseNavBarId");

                    b.ToTable("WorkShowCaseNavBarItems");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.WorkShowCaseService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkShowCaseNavBarItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkShowCaseNavBarItemId");

                    b.ToTable("WorkShowCaseServices");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.WorkingProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SubTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("WorkingProcesses");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.WorkingProcessItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkingProcessId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkingProcessId");

                    b.ToTable("WorkingProcessItems");
                });

            modelBuilder.Entity("Core.Domains.Languages.StringResource", b =>
                {
                    b.HasOne("Core.Domains.Languages.Language", "Language")
                        .WithMany("StringResources")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Core.HomePage.HomePage", b =>
                {
                    b.HasOne("Core.HomePage.HomePageItems.ChooseUs", "ChooseUs")
                        .WithMany()
                        .HasForeignKey("ChooseUsId");

                    b.HasOne("Core.HomePage.HomePageItems.ClientSays", "ClientSays")
                        .WithMany()
                        .HasForeignKey("ClientSaysId");

                    b.HasOne("Core.HomePage.HomePageInfo", "HomePageInfo")
                        .WithMany()
                        .HasForeignKey("HomePageInfoId");

                    b.HasOne("Core.HomePage.HomePageItems.OurCompany", "OurCompany")
                        .WithMany()
                        .HasForeignKey("OurCompanyId");

                    b.HasOne("Core.HomePage.HomePageItems.OurEmployees", "OurEmployees")
                        .WithMany()
                        .HasForeignKey("OurEmployeesId");

                    b.HasOne("Core.HomePage.HomePageItems.RegularBlogs", "RegularBlogs")
                        .WithMany()
                        .HasForeignKey("RegularBlogsId");

                    b.HasOne("Core.HomePage.HomePageItems.Service", "Services")
                        .WithMany()
                        .HasForeignKey("ServicesId");

                    b.HasOne("Core.HomePage.HomePageItems.Slider", "Slider")
                        .WithMany()
                        .HasForeignKey("SliderId");

                    b.HasOne("Core.HomePage.HomePageItems.WhoWeAre", "WhoWeAre")
                        .WithMany()
                        .HasForeignKey("WhoWeAreId");

                    b.HasOne("Core.HomePage.HomePageItems.WorkShowCase", "WorkShowCase")
                        .WithMany()
                        .HasForeignKey("WorkShowCaseId");

                    b.HasOne("Core.HomePage.HomePageItems.WorkingProcess", "WorkingProcess")
                        .WithMany()
                        .HasForeignKey("WorkingProcessId");

                    b.Navigation("ChooseUs");

                    b.Navigation("ClientSays");

                    b.Navigation("HomePageInfo");

                    b.Navigation("OurCompany");

                    b.Navigation("OurEmployees");

                    b.Navigation("RegularBlogs");

                    b.Navigation("Services");

                    b.Navigation("Slider");

                    b.Navigation("WhoWeAre");

                    b.Navigation("WorkShowCase");

                    b.Navigation("WorkingProcess");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.ClientSaysItem", b =>
                {
                    b.HasOne("Core.HomePage.HomePageItems.ClientSays", "ClientSays")
                        .WithMany("ClientSaysItems")
                        .HasForeignKey("ClientSaysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientSays");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.FooterService", b =>
                {
                    b.HasOne("Core.HomePage.HomePageItems.Footer", "Footer")
                        .WithMany("Services")
                        .HasForeignKey("FooterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Footer");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.Image", b =>
                {
                    b.HasOne("Core.HomePage.HomePageItems.ServiceItem", null)
                        .WithMany("Images")
                        .HasForeignKey("ServiceItemId");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.NavBarItem", b =>
                {
                    b.HasOne("Core.HomePage.HomePage", null)
                        .WithMany("NavBarItems")
                        .HasForeignKey("HomePageId");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.NavBarItemSubItem", b =>
                {
                    b.HasOne("Core.HomePage.HomePageItems.NavBarItem", null)
                        .WithMany("NavBarItemSubItems")
                        .HasForeignKey("NavBarItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.OurEmployeesItem", b =>
                {
                    b.HasOne("Core.HomePage.HomePageItems.OurEmployees", "OurEmployees")
                        .WithMany("OurEmployeesItems")
                        .HasForeignKey("OurEmployeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OurEmployees");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.Question", b =>
                {
                    b.HasOne("Core.HomePage.HomePageItems.ChooseUs", null)
                        .WithMany("Questions")
                        .HasForeignKey("ChooseUsId");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.QuickLink", b =>
                {
                    b.HasOne("Core.HomePage.HomePageItems.Footer", "Footer")
                        .WithMany("QuickLinks")
                        .HasForeignKey("FooterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Footer");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.RegularBlogsItem", b =>
                {
                    b.HasOne("Core.HomePage.HomePageItems.RegularBlogs", "RegularBlogs")
                        .WithMany("RegularBlogsItems")
                        .HasForeignKey("RegularBlogsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegularBlogs");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.ServiceItem", b =>
                {
                    b.HasOne("Core.HomePage.HomePageItems.Service", null)
                        .WithMany("ServiceItem")
                        .HasForeignKey("ServiceId");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.SocialLink", b =>
                {
                    b.HasOne("Core.HomePage.HomePageInfo", null)
                        .WithMany("SocialLinks")
                        .HasForeignKey("HomePageInfoId");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.WhoWeAreItem", b =>
                {
                    b.HasOne("Core.HomePage.HomePageItems.WhoWeAre", "WhoWeAre")
                        .WithMany("WhoWeAreItem")
                        .HasForeignKey("WhoWeAreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WhoWeAre");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.WorkShowCaseNavBar", b =>
                {
                    b.HasOne("Core.HomePage.HomePageItems.WorkShowCase", "WorkShowCase")
                        .WithOne("WorkShowCaseNavBar")
                        .HasForeignKey("Core.HomePage.HomePageItems.WorkShowCaseNavBar", "WorkShowCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkShowCase");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.WorkShowCaseNavBarItem", b =>
                {
                    b.HasOne("Core.HomePage.HomePageItems.WorkShowCaseNavBar", "WorkShowCaseNavBar")
                        .WithMany("WorkShowCaseNavBarItems")
                        .HasForeignKey("WorkShowCaseNavBarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkShowCaseNavBar");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.WorkShowCaseService", b =>
                {
                    b.HasOne("Core.HomePage.HomePageItems.WorkShowCaseNavBarItem", "WorkShowCaseNavBarItem")
                        .WithMany("WorkShowCaseServices")
                        .HasForeignKey("WorkShowCaseNavBarItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkShowCaseNavBarItem");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.WorkingProcessItem", b =>
                {
                    b.HasOne("Core.HomePage.HomePageItems.WorkingProcess", null)
                        .WithMany("WorkingProcessItems")
                        .HasForeignKey("WorkingProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domains.Languages.Language", b =>
                {
                    b.Navigation("StringResources");
                });

            modelBuilder.Entity("Core.HomePage.HomePage", b =>
                {
                    b.Navigation("NavBarItems");
                });

            modelBuilder.Entity("Core.HomePage.HomePageInfo", b =>
                {
                    b.Navigation("SocialLinks");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.ChooseUs", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.ClientSays", b =>
                {
                    b.Navigation("ClientSaysItems");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.Footer", b =>
                {
                    b.Navigation("QuickLinks");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.NavBarItem", b =>
                {
                    b.Navigation("NavBarItemSubItems");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.OurEmployees", b =>
                {
                    b.Navigation("OurEmployeesItems");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.RegularBlogs", b =>
                {
                    b.Navigation("RegularBlogsItems");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.Service", b =>
                {
                    b.Navigation("ServiceItem");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.ServiceItem", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.WhoWeAre", b =>
                {
                    b.Navigation("WhoWeAreItem");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.WorkShowCase", b =>
                {
                    b.Navigation("WorkShowCaseNavBar");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.WorkShowCaseNavBar", b =>
                {
                    b.Navigation("WorkShowCaseNavBarItems");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.WorkShowCaseNavBarItem", b =>
                {
                    b.Navigation("WorkShowCaseServices");
                });

            modelBuilder.Entity("Core.HomePage.HomePageItems.WorkingProcess", b =>
                {
                    b.Navigation("WorkingProcessItems");
                });
#pragma warning restore 612, 618
        }
    }
}
